version: "3.8"

services:
  stock_ticker:
    build:
      context: .
      dockerfile: build/php.dockerfile
    container_name: stock_ticker
    hostname: php
    volumes:
      - .:/srv/stock-ticker:delegated
