version: "3.8"

services:
  stock_ticker:
    build:
      context: .
      dockerfile: devops/dev/php.dockerfile
    container_name: stock_ticker
    hostname: php
    volumes:
      - .:/srv/StockTicker:delegated
